### PR TITLE
Tyler Evans dev to be merged

### PR DESCRIPTION
**Pull request by TylerEvans-Dev**
here is the complete material for the merge.

### CODE REVIEW

**Comment by corey-buchanan** [comment]
Sorry it took me a while to get to your review.

There are a few things that need fixing. The FSM has the issue of if two trains (one nb and one sb) approach and only one of them leaves, the arms go back up and the alarm shuts off. The FSM table will help you capture those states, but the formatting of the FSM table needs to be fixed. You can look at ours for an example (https://github.com/uofu-emb/2024-Lab09-Corey-Phelan/blob/main/verification%20notes.md - though I won't claim that it's 100% correct.) The wording of the assignment and the instructions can be a little confusing though. The columns arms_down-northbound_present indicates the current state. The columns north_approach-ringing are events and the numbers indicate which state the FSM should transition to if the event is raised in that state. You seem to have good invariants, if an event in a certain state violates the invariant, you can put it in that column. Safety_hazard should only be filled in if the state itself violates an invariant.

*Note that state number 4 is actually valid, where the arms have gone back up after the train leaves, but the alarm is still ringing because 10 seconds hasn't elapsed.

From that FSM, you should be able to translate each valid row into a state and use the column events to build your transitions. Hopefully this helps give you enough to add those extra states needed. Sorry it took me so long to get back to you.

**Comment by TylerEvans-Dev** [comment]
Alright, things should be fixed. please tell me if there are any issues,
Thanks,
Tyler.

**Comment by TylerEvans-Dev** [comment]
Due to the fact that is has been an entire month and I tried my best to fix this I am going to close the pull request because I want to be done with the lab and move on.

**Review by phelanhobbs — APPROVED** [review]
Apologies, I had just reviewed a few PRs I had and had thought that I gotten to yours. Apologies again.

**Comment by TylerEvans-Dev** [comment]
no worries.

**Comment by corey-buchanan** [comment]
This looks better!

**Pull request merged**
